name: Deploy on EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/${{ secrets.EC2_USERNAME }}/fast-api-app || git clone https://github.com/plutack/fastapi-book-project.git fast-api-app
          cd /home/${{ secrets.EC2_USERNAME }}/fast-api-app
          git pull origin main

          docker build --no-cache -t fast-api-app:latest .
          docker-compose up -d --no-deps --force-recreate web 
