name: Deploy on EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/${{ secrets.EC2_USERNAME }} || exit 1
          if [ ! -d "fast-api-app" ]; then
            git clone https://github.com/plutack/fastapi-book-project.git fast-api-app
          fi
          cd fast-api-app
          git pull origin main

          docker-compose down
          docker-compose build --no-cache
          docker-compose up -d
